crud_comment/blogproject/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name='blog'
urlpatterns = [
    path('', views.main, name="main"),
    path('new/', views.new, name="new"),
    path('detail/<int:article_id>', views.detail, name="detail"),
    path('edit/<int:article_id>', views.edit, name="edit"),
    path('delete/<int:article_id>', views.delete, name="delete"),
    path('comment_delete/<int:article_id>/<int:comment_id>', views.comment_delete, name="comment_delete"),     
    path('comment_edit/<int:comment_id>', views.comment_edit, name="comment_edit"),
    path('hashtag/', views.hashtagform, name='hashtag'),
    path('search/<int:hashtag_id>/', views.search, name="search"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud_comment/blogproject/blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
# from blog import views
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.main, name="main"),
    path('', include("blog.urls")),
]

crud_comment/blogproject/blog/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    published_at = models.DateTimeField(null=False)
    hashtags = models.ManyToManyField('Hashtag', blank=True)
    image = models.ImageField(upload_to='images/', blank=True)
    
    def __str__(self):
        return self.title

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments")
    content = models.CharField(max_length=100)

    def __str__(self):
        return self.content

class Hashtag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

crud_comment/blogproject/blog/forms.py
from django import forms
from .models import Article, Comment, Hashtag
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "hashtags", "image"]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

class HashtagForm(forms.ModelForm):
    class Meta:
        model = Hashtag
        fields = ['name']

crud_comment/blogproject/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from .models import Article, Comment, Hashtag
from .forms import ArticleForm, CommentForm, HashtagForm

# Create your views here.
def main(request):
    articles = Article.objects.all()
    hashtags = Hashtag.objects.all()
    medias = Article.objects
    return render(request, 'blog/main.html', {'articles':articles, 'hashtags': hashtags, 'medias': medias})

def detail(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
                comment = form.save(commit=False) #아직 저장x
                comment.article = article # 모델에서 객체를 받기로함
                comment.content = form.cleaned_data["content"] #내용을 입력해라
                comment.save() # 저장
                return redirect("blog:detail", article_id) #aritcle_id로 참조하고 디테일페이지로 감
    else:
        form = CommentForm()
        return render(request, "blog/detail.html", {"article":article, "form":form})


def new(request):
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.title = form.cleaned_data["title"]
            article.content = form.cleaned_data["content"]
            article.published_at = timezone.now()
            article.save()
            form.save_m2m()
            return redirect("blog:main")
    else:
        form = ArticleForm()
        return render(request, "blog/new.html", {'form':form})

def edit(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if ("image" in request.FILES) and ("image-clear" in request.POST):
            del request.FILES["image"]
        if form.is_valid():
            article = form.save(commit=False)
            article.title = form.cleaned_data["title"]
            article.content = form.cleaned_data["content"]
            article.published_at = timezone.now()
            article.save()
            return redirect("blog:detail", article.id)
    else:
        form = ArticleForm(instance=article)
        return render(request, "blog/new.html", {'form':form})

def delete(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    article.delete()
    return redirect("blog:main")

def comment_delete(request, article_id, comment_id):
        comment = get_object_or_404(Comment, id=comment_id) #id또는 pk
        comment.delete()
        return redirect("blog:detail", article_id)

# def comment_delete(request, comment_id):
#         comment = get_object_or_404(comment, comment_id)
#         article_id = comment.article.id
#         comment.delete()
#         return redirect("blog:detail", article_id)

# def comment_delete(request, comment_id):
#         comment = get_object_or_404(comment, comment_id)
#         comment.delete()
#         return redirect("blog:detail", comment.article.id)
# 2,3번 방법으로 하면 article_id는 안넘겨주어도 괜찮음

def comment_edit(request, comment_id):
        comment = get_object_or_404(Comment, id=comment_id)
        if request.method == "POST":
            form = CommentForm(request.POST, instance=comment)
            if form.is_valid():
                    comment = form.save(commit=False)
                    comment.content = form.cleaned_data["content"]
                    comment.save()
                    return redirect("blog:detail", comment.article.id)
        else:
            form = CommentForm(instance=comment) #기본으로 정해주는 값을 지정해주는거
            return render(request, "blog/new.html", {"form":form})

def hashtagform(request, hashtag=None):
        if request.method == 'POST':
                form = HashtagForm(request.POST, instance=hashtag)
                if form.is_valid():
                        hashtag = form.save(commit=False)
                        if Hashtag.objects.filter(name=form.cleaned_data['name']):
                                form = HashtagForm()
                                error_message = "이미 존재하는 해시태그 입니다."
                                return render(request, 'blog/hashtag.html', {'form': form, "error_message": error_message})
                        else:
                                hashtag.name = form.cleaned_data['name']
                                hashtag.save()
                                return redirect('blog:main')
        else:
                form = HashtagForm(instance=hashtag)
                return render(request, 'blog/hashtag.html', {'form': form})

def search(request, hashtag_id):
    hashtag = get_object_or_404(Hashtag, pk=hashtag_id)
    return render(request, 'blog/search.html', {'hashtag': hashtag})

crud_comment/blogproject/blog/templates/blog/detail.html
{% extends 'index.html' %}
{% block content %}
<h1>{{ article.title }}</h1>
<p>{{ article.content }}</p>
<p>{{ article.published_at }}</p>
{% if article.image %}
    <img class="card-img-top" src="{{ article.image.url }}" alt="Card image cap">
{% endif %}

{% for hashtag in article.hashtags.all %}
    <span>{{ hashtag.name }}</span>
{% endfor %} <br>
<a href="{% url 'blog:edit' article.id %}">수정</a>
<a href="{% url 'blog:delete' article.id %}">삭제</a>
<hr>
{% for comment in article.comments.all %}
<p>{{ comment.content }}</p>
<a href="{% url 'blog:comment_edit' comment.id %}">수정</a>
<a href="{% url 'blog:comment_delete' article.id comment.id %}">삭제</a>
<hr>
{% endfor %}
<hr>
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="submit">
</form>
{% endblock %}

crud_comment/blogproject/blog/templates/blog/hashtag.html
{% extends 'index.html' %}
{% block content %}
    <h1>New Hashtag</h1>
    {{ error_message }}
    <form method="POST">
        {% csrf_token %}
        <table>
                {{form.as_table}}
        </table>
        <input class="btn btn-dark" type="submit" value="제출하기">
    </form>
{% endblock %}

crud_comment/blogproject/blog/templates/blog/main.html
{% extends 'index.html' %}

{% block content %}
    {% if articles %}
        <table class="table table-bordered" style="text-align: center;">
            <thead>
            <tr>
                <th scope="col" style="width: 10%;">글 번호</th>
                <th scope="col" style="width: 20%;">날짜</th>
                <th scope="col" style="width: 20%;">제목</th>
                <th scope="col" style="width: 50%;">내용</th>
            </tr>
            </thead>
            <tbody>
            {% for article in articles %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ article.published_at }}</td>
                    <td><a href="{% url 'blog:detail' article.id %}">{{ article.title | truncatechars:10 }}</a></td>
                    <td>{{ article.content | truncatechars:30 }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

crud_comment/blogproject/blog/templates/blog/new.html
{% extends 'index.html' %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Title</p>{{ form.title }}<br><br>
    <p>Content</p>{{ form.content }}<br><br>
    <p>Hashtags</p>{{ form.hashtags }}<br><br>
    <p>Image</p>{{ form.image }}<br><br>
    <br><input type="submit" value="submit">
</form>
{% endblock %}

crud_comment/blogproject/blog/templates/blog/search.html
{% extends 'index.html' %}
{% block content %}
      {% for article in hashtag.article_set.all %}
      <div class="post-preview">
        <a href="{% url 'blog:detail' article.id %}">
          <h2 class="post-title">
            {{ article.title }}
          </h2>
          <h3 class="post-subtitle">
            {{ article.content }}
          </h3>
        </a>
        <p class="post-meta">
          {{ article.published_at }}</p>
      </div>
      <hr>
      {% endfor %}

      <div class="dropdown">
        <button class="btn btn-primary float-right dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Hashtag 검색
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          {% for hashtag in hashtags.all %}
          <a href="{% url 'blog:search' hashtag.id %}">{{ hashtag.name }}</a>
          {% endfor %}
        </div>
      </div>
{% endblock %}

crud_comment/blogproject/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>멋사 게시판</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
  

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'blog:main' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">멋사 게시판</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Interface
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'blog:new' %}">
          <i class="fas fa-fw fa-cog"></i>
          <span>글쓰기</span>
        </a>
      </li>

      <!-- Nav Item - Utilities Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'blog:main' %}">
          <i class="fas fa-fw fa-wrench"></i>
          <span>홈</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'blog:hashtag' %}">
          <i class="fas fa-fw fa-wrench"></i>
          <span>해시태그 추가</span>
        </a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            <!-- Nav Item - Alerts -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">3+</span>
              </a>
              <!-- Dropdown - Alerts -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                  Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-primary">
                      <i class="fas fa-file-alt text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 12, 2019</div>
                    <span class="font-weight-bold">A new monthly report is ready to download!</span>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-success">
                      <i class="fas fa-donate text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 7, 2019</div>
                    $290.29 has been deposited into your account!
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-warning">
                      <i class="fas fa-exclamation-triangle text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 2, 2019</div>
                    Spending Alert: We've noticed unusually high spending for your account.
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
              </div>
            </li>

            <!-- Nav Item - Messages -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter">7</span>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                  Message Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
                    <div class="status-indicator bg-success"></div>
                  </div>
                  <div class="font-weight-bold">
                    <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
                    <div class="small text-gray-500">Emily Fowler · 58m</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
                    <div class="status-indicator"></div>
                  </div>
                  <div>
                    <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
                    <div class="small text-gray-500">Jae Chun · 1d</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
                    <div class="status-indicator bg-warning"></div>
                  </div>
                  <div>
                    <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
                    <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
                    <div class="status-indicator bg-success"></div>
                  </div>
                  <div>
                    <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
                    <div class="small text-gray-500">Chicken the Dog · 2w</div>
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
              </div>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Valerie Luna</span>
                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div>
          {% block content %}{% endblock %}
          </div>

          <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
          <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>

</html>